org: won2free
app: won2free
service: won2free-core
frameworkVersion: '4'

stages:
  default:
    params:
      schedule1: ${file(./serverless.env.yml):dev_schedule1}
      schedule2: ${file(./serverless.env.yml):dev_schedule2}
      schedule_daily: ${file(./serverless.env.yml):schedule_daily}
  prod:
    params:
      schedule1: ${file(./serverless.env.yml):prod_schedule1}
      schedule2: ${file(./serverless.env.yml):prod_schedule2}

provider:
  name: aws
  runtime: python3.10
  region: ap-east-1
  memorySize: 128
  timeout: 10
  versionFunctions: true
  logRetentionInDays: 7
  environment:
    QUEUE_NAME: ${file(./serverless.env.yml):QUEUE_NAME}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:DescribeTable
            - dynamodb:CreateTable
          Resource: "*"
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
            - sqs:SendMessage
            - sqs:GetQueueUrl
            - sqs:DeleteMessage
            - sqs:CreateQueue
          Resource: "arn:aws:sqs:${aws:region}:${aws:accountId}:${self:provider.environment.QUEUE_NAME}"

functions:
  init:
    handler: init/lambda_function.lambda_handler
    timeout: 60
  job:
    handler: job/job_funding.lambda_handler
    events:
      - schedule: ${param:schedule1}
  job-auto-rate:
    handler: job/job_autorate.lambda_handler
    events:
      - schedule: ${param:schedule_daily}
  reactor:
    handler: reactor/lambda_function.lambda_handler
    layers:
      - arn:aws:lambda:${aws:region}:${aws:accountId}:layer:${file(./serverless.env.yml):LAYER_NAME}
      - arn:aws:lambda:ap-east-1:839552336658:layer:AWSSDKPandas-Python310:19
    events:
      - schedule: ${param:schedule2}
    environment:
      QUEUE_NAME: ${file(./serverless.env.yml):QUEUE_NAME}
      TG_TOKEN: ${file(./serverless.env.yml):TG_TOKEN}
    memorySize: 256
    timeout: 30
package:
  # Directories and files to include in the deployed package
  patterns:
    - "!node_modules"
    - '!.git/**'
    - '!.travis.yml'
    - '!package.json'
    - '!package-lock.json'
    - '!requirements.txt'
    - '!serverless.env.yml'